# Generated by Django 5.1.5 on 2025-05-26 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_delivery_date'),
        ('reviews', '0003_review_order_alter_review_bouquet_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='order',
            field=models.ForeignKey(limit_choices_to={'status': 'completed'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orders.order', verbose_name='Заказ'),
        ),
    ]
