# Generated by Django 5.1.5 on 2025-05-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('consists', models.TextField(max_length=100, verbose_name='Содержит')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('pic1', models.ImageField(upload_to='bouquets/', verbose_name='Фото1')),
                ('pic2', models.ImageField(upload_to='bouquets/', verbose_name='Фото2')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='Бестселлер')),
            ],
        ),
    ]
