# Generated by Django 5.1.5 on 2025-05-23 05:48
from django.db import migrations
from decimal import Decimal


def set_cost_price(apps, schema_editor):
    Bouquet = apps.get_model('catalog', 'Bouquet')
    for bouquet in Bouquet.objects.all():
        bouquet.cost_price = bouquet.price * Decimal(0.7)
        bouquet.save()


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0002_bouquet_cost_price'),
    ]

    operations = [
        migrations.RunPython(set_cost_price),
    ]
