# Generated by Django 5.1.5 on 2025-05-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20250523_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquet',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Себестоимость'),
        ),
    ]
