# Generated by Django 5.1.5 on 2025-05-21 11:13

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 5, 21, 13, 13, 47, 182687, tzinfo=datetime.timezone.utc))]),
        ),
    ]
