# Generated by Django 5.1.5 on 2025-05-22 10:20

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_delivery_type_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 5, 22, 12, 20, 54, 828012, tzinfo=datetime.timezone.utc))]),
        ),
    ]
