# Generated by Django 5.1.5 on 2025-05-22 15:39

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_recipient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 5, 22, 17, 39, 54, 499524, tzinfo=datetime.timezone.utc))]),
        ),
    ]
