# Generated by Django 5.1.5 on 2025-05-26 12:37

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 5, 26, 14, 37, 6, 978982, tzinfo=datetime.timezone.utc))]),
        ),
    ]
