# Generated by Django 5.1.5 on 2025-05-27 17:09

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 5, 27, 19, 9, 34, 693422, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('prepaid', 'Предоплачен'), ('pending', 'В обработке'), ('confirmed', 'Подтверждён'), ('processing', 'В доставке'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='prepaid', max_length=20),
        ),
    ]
